<?php

/*
    Sessions
    - Session Is Stored On The Server
    - Session Store Only A User Key In Cookie To Know Its You
    - Key Are Generated By PHP Engine So Its Almost Impossible To Guess
    - You Need To Add It Before Any Output
  */

// using this function will allow us to use the super global variable $_SESSION to store and retrieve
session_start();

// session values will be deleted at the end of the session
$_SESSION["name"] = "hasan";
$_SESSION["id"] = "9711";
$_SESSION["age"] = "26";
$_SESSION["job"] = "Unicorn Owner 🦄";


echo '<pre>';
print_r($_SESSION);
echo '</pre>';

echo '<a href="profile.php">profile</a>';
